# Generated by Django 5.1.6 on 2025-03-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_grouppermission_groupspermissions_and_more'),
        ('companies', '0003_rename_users_enterprise_user_remove_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
